# Generated by Django 4.2.30 on 2026-08-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('internship_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mentor_name', models.CharField(max_length=200)),
                ('mentor_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], default='Ongoing', max_length=20)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=10)),
                ('final_evaluation', models.TextField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('tasks_done', models.TextField()),
                ('mentor_feedback', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='applications.internship')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
    ]
