# Generated by Django 4.2.30 on 2026-08-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('provider', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='skills.skill')),
            ],
            options={
                'ordering': ['skill', 'level'],
            },
        ),
    ]
