# Generated by Django 4.2.30 on 2026-08-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='data_status',
            field=models.CharField(choices=[('DEMO', 'Demo Opportunity'), ('NEEDS_VERIFICATION', 'Verify Availability'), ('VERIFIED', 'Verified Opportunity')], default='NEEDS_VERIFICATION', help_text='Indicates data verification status.', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State or Region', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Full-Time Job'), ('Research', 'Research Opportunity'), ('Clinical Training', 'Clinical Training'), ('Industry Training', 'Industry Training'), ('Fellowship', 'Fellowship'), ('Ayurvedic Wellness', 'Ayurvedic Wellness Opportunity'), ('Academic Collaboration', 'Academic / Research Collaboration'), ('FDP', 'Faculty Development Program (FDP)')], max_length=50),
        ),
    ]
