# Generated by Django on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_data_status_opportunity_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[
                ('Internship', 'Internship'),
                ('Job', 'Full-Time Job'),
                ('Research', 'Research Opportunity'),
                ('Clinical Training', 'Clinical Training'),
                ('Industry Training', 'Industry Training'),
                ('Fellowship', 'Fellowship'),
                ('Ayurvedic Wellness', 'Ayurvedic Wellness Opportunity'),
                ('Academic Collaboration', 'Academic / Research Collaboration'),
                ('FDP', 'Faculty Development Program (FDP)'),
                ('Pharma R&D', 'Pharmaceutical / R&D Opportunity'),
                ('Hospital Clinical', 'Hospital / Clinical Opportunity'),
                ('Hospital Admin', 'Hospital / Healthcare Administration'),
                ('Medical Content', 'Medical Content & Documentation Opportunity'),
                ('Public Health', 'Public Health Opportunity'),
                ('Startup Support', 'Entrepreneurship / Startup Support Opportunity'),
            ], max_length=50),
        ),
    ]
