# Scratch script to expand Question Bank in seed_data.py
import re

seed_path = r"c:\ayurveda project\students\management\commands\seed_data.py"

with open(seed_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Split at VALIDATION_QUESTIONS_DATA = [
parts = content.split("VALIDATION_QUESTIONS_DATA = [")
header = parts[0]

new_validation_data_and_command = '''VALIDATION_QUESTIONS_DATA = [
    # =========================================================================
    # 1. AYURVEDA KNOWLEDGE (10 Questions)
    # =========================================================================
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'According to classical Charaka Samhita, what constitutes the fundamental Trisutra Ayurveda (the three pillars of Ayurvedic medicine)?',
        'question_type': 'mcq',
        'option_a': 'Vata, Pitta, Kapha',
        'option_b': 'Hetu (Etiology), Linga (Symptomatology), and Aushadha (Therapeutics)',
        'option_c': 'Ahara, Nidra, Brahmacharya',
        'option_d': 'Satva, Raja, Tama',
        'correct_answer': 'B',
        'explanation': 'Trisutra Ayurveda comprises Hetu (causes of disease and health), Linga (clinical signs and symptoms), and Aushadha (appropriate preventive and curative therapies).',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'During the physiological process of digestion (Avasthapaka), which Dosha is predominantly manifested in the initial Madhura Avasthapaka occurring in the Amashaya?',
        'question_type': 'mcq',
        'option_a': 'Vata Dosha',
        'option_b': 'Pitta Dosha',
        'option_c': 'Kapha Dosha',
        'option_d': 'Rakta Dhatu',
        'correct_answer': 'C',
        'explanation': 'In the first stage of digestion (Madhura Avasthapaka in the stomach), frothy Kapha is produced due to the sweet and unctuous nature of food.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'According to the classical Dhatuposhana Nyaya (theory of tissue nourishment), which tissue is directly formed after the metabolic transformation of Mamsa Dhatu by Mamsadhatvagni?',
        'question_type': 'mcq',
        'option_a': 'Rakta Dhatu',
        'option_b': 'Meda Dhatu',
        'option_c': 'Asthi Dhatu',
        'option_d': 'Majja Dhatu',
        'correct_answer': 'B',
        'explanation': 'The sequential tissue formation order is Rasa -> Rakta -> Mamsa -> Meda -> Asthi -> Majja -> Shukra. Meda Dhatu is formed following Mamsa Dhatu.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'A person presenting with quick comprehension but fast forgetting, dry and rough skin, intolerance to cold breeze, and irregular bowel habits exhibits the classical constitutional traits of which Prakriti?',
        'question_type': 'mcq',
        'option_a': 'Vata Prakriti',
        'option_b': 'Pitta Prakriti',
        'option_c': 'Kapha Prakriti',
        'option_d': 'Sama Prakriti',
        'correct_answer': 'A',
        'explanation': 'Vata Prakriti individuals exhibit Laghu, Chala, Ruksha, and Sheeta qualities leading to swift cognition with rapid forgetfulness and irregular bowel movements (Vishamagni).',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'In the six stages of disease progression (Shat Kriya Kala) according to Sushruta, what occurs during the fourth stage known as Sthanasamshraya?',
        'question_type': 'mcq',
        'option_a': 'Accumulation of Doshas in their native anatomical seats',
        'option_b': 'Dosha-Dushya Sammurchhana (relocation and lodgement of circulating Doshas into defective Khavaigunya sites, initiating prodromal symptoms)',
        'option_c': 'Overflow and systemic spread of excited Doshas through circulation',
        'option_d': 'Final stage of chronic ulceration and structural tissue destruction',
        'correct_answer': 'B',
        'explanation': 'Sthanasamshraya is the crucial fourth stage where circulating aggravated Doshas lodge in vulnerable sites (Khavaigunya) causing Dosha-Dushya Sammurchhana and Poorvaroopa (premonitory signs).',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'Which fundamental state of Agni is characterized by erratic, unpredictable digestion—sometimes digesting heavy meals quickly and other times causing bloating and indigestion from light food?',
        'question_type': 'mcq',
        'option_a': 'Samagni',
        'option_b': 'Mandagni',
        'option_c': 'Vishamagni',
        'option_d': 'Tikshnagni',
        'correct_answer': 'C',
        'explanation': 'Vishamagni is influenced by irregular Vata Dosha, causing unpredictable fluctuation in digestive and metabolic capacity.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'What are the four classical types of Srotodushti (pathological micro-channel dysfunctions) described in Charaka Samhita?',
        'question_type': 'mcq',
        'option_a': 'Vataja, Pittaja, Kaphaja, Sannipataja',
        'option_b': 'Atipravritti (excessive flow), Sanga (obstruction), Siragranthi (nodular dilatation), and Vimargagamana (extravasation / flow into abnormal channels)',
        'option_c': 'Kshaya, Vriddhi, Sama, Nirama',
        'option_d': 'Alpa, Madhya, Uttama, Pravara',
        'correct_answer': 'B',
        'explanation': 'The four classical Srotodushti manifestations are Atipravritti, Sanga, Siragranthi, and Vimargagamana.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'What is the prime qualitative essence (Sara) of all seven bodily Dhatus that provides biological immunity (Vyadhikshamatva), vitality, and cellular resilience?',
        'question_type': 'mcq',
        'option_a': 'Rakta',
        'option_b': 'Majja',
        'option_c': 'Ojas',
        'option_d': 'Kleda',
        'correct_answer': 'C',
        'explanation': 'Ojas is the quintessence of all Sapta Dhatus, governing natural and acquired immunity (Bala / Vyadhikshamatva) and constitutional strength.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'A patient experiences persistent burning sensation (Daha), intense thirst (Trishna), yellow discoloration of urine and sclera (Peetavabhasa), and irritability. Which physiological entity is predominantly increased?',
        'question_type': 'case_study',
        'case_context': '42-year-old chef working near intense cooking ovens, drinks hot sour beverages, presents with sour eructations, hot flushes, and red itchy urticarial patches.',
        'option_a': 'Vata Vriddhi',
        'option_b': 'Pitta Vriddhi',
        'option_c': 'Kapha Vriddhi',
        'option_d': 'Meda Kshaya',
        'correct_answer': 'B',
        'explanation': 'Daha, Trishna, Peetavabhasa, and sour/burning manifestations are cardinal symptoms of Pitta Vriddhi caused by Ushna-Tikshna exposures.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Ayurveda Knowledge',
        'question_text': 'According to the Ayurvedic seasonal rhythm (Ritucharya), during which season is the physiological accumulation (Sanchaya) of Pitta Dosha observed, followed by its natural aggravation (Prakopa) in Sharad Ritu?',
        'question_type': 'mcq',
        'option_a': 'Grishma Ritu (Summer)',
        'option_b': 'Varsha Ritu (Monsoon)',
        'option_c': 'Shishira Ritu (Late Winter)',
        'option_d': 'Vasanta Ritu (Spring)',
        'correct_answer': 'B',
        'explanation': 'Varsha Ritu causes Pitta Sanchaya due to acidic environmental waters and weakened Agni, which then undergoes violent Prakopa in Sharad Ritu under direct sunlight.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },

    # =========================================================================
    # 2. CLINICAL SKILLS (10 Questions)
    # =========================================================================
    {
        'skill': 'Clinical Skills',
        'question_text': 'A 45-year-old patient presents with pain and stiffness in weight-bearing joints that worsens during cold weather, accompanied by audible joint crepitus (Sandhisphutana). The pulse palpation demonstrates a rapid, serpentine movement (Sarpa Nadi). What is the primary diagnosis?',
        'question_type': 'case_study',
        'case_context': '45-year-old male, bilateral knee pain for 8 months, no morning stiffness exceeding 15 minutes, crepitus positive on flexion, no systemic fever.',
        'option_a': 'Amavata (Rheumatoid arthritis) with Pitta dominance',
        'option_b': 'Sandhigata Vata (Osteoarthritis) with predominant Vata vitiation',
        'option_c': 'Vatarakta (Gouty arthritis) with Rakta involvement',
        'option_d': 'Kroshtukasheersha (Effusion of knee)',
        'correct_answer': 'B',
        'explanation': 'Sandhisphutana (crepitus), pain aggravated by cold without systemic Ama or prolonged morning stiffness, along with Sarpa Nadi, confirms Sandhigata Vata.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'In the classical Dashavidha Rogi Pariksha (tenfold patient examination), which parameter specifically evaluates the patient mental resilience, willpower, and tolerance to pain?',
        'question_type': 'mcq',
        'option_a': 'Satmya Pariksha',
        'option_b': 'Satva Pariksha',
        'option_c': 'Bala Pariksha',
        'option_d': 'Vaya Pariksha',
        'correct_answer': 'B',
        'explanation': 'Satva Pariksha assesses the mental strength of the patient (Pravara, Madhyama, or Avara Satva) which determines their pain threshold and ability to comply with rigorous therapies.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'Which classical movement of the radial pulse (Nadi Gati) is canonically described for predominant Pitta Dosha vitiation?',
        'question_type': 'mcq',
        'option_a': 'Sarpa Gati (Serpentine crawl)',
        'option_b': 'Manduka Gati (Frog-like jumping pulse)',
        'option_c': 'Hamsa Gati (Graceful swan-like glide)',
        'option_d': 'Kaka Gati (Crow-like erratic peck)',
        'correct_answer': 'B',
        'explanation': 'Pitta Nadi is characterized as Manduka Gati (jumping like a frog) due to the Tikshna and Ushna attributes of Pitta causing sudden forceful pulse beats.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'A patient with persistent productive cough reports sweet taste in the mouth, excessive mucoid expectoration, heaviness in the chest, and loss of appetite. Sputum is thick, white, and unctuous. What is the clinical diagnosis?',
        'question_type': 'case_study',
        'case_context': '32-year-old female, chronic productive cough for 3 weeks, aggravated after cold drinks and sleep, tongue heavily coated with white Ama.',
        'option_a': 'Vataja Kasa',
        'option_b': 'Pittaja Kasa',
        'option_c': 'Kaphaja Kasa',
        'option_d': 'Kshataja Kasa',
        'correct_answer': 'C',
        'explanation': 'Thick unctuous expectoration, heaviness, sweet mouth taste, and loss of appetite are hallmark features of Kaphaja Kasa.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'In the Ashta Sthana Pariksha (eightfold clinical examination), what clinical feature of the tongue (Jihva) indicates a Sama (Ama-laden) systemic state?',
        'question_type': 'mcq',
        'option_a': 'Clean, pink, moist, and freely mobile tongue without coating',
        'option_b': 'Heavily coated with thick greasy adherent fur, loss of papillae definition, and foul breath',
        'option_c': 'Hyper-red tongue with multiple burning erosions',
        'option_d': 'Cracked, dry, blackish-rough tongue with tremors',
        'correct_answer': 'B',
        'explanation': 'Sama Jihva is marked by thick, greasy coating (Malavrita) and impaired taste sensation, reflecting systemic Ama accumulation in the gastrointestinal tract.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'A 38-year-old male presents with sudden onset of severe excruciating pain, burning sensation, swelling, and purplish erythema at the right first metatarsophalangeal joint that developed overnight after alcohol and high-protein seafood consumption. What is the condition?',
        'question_type': 'case_study',
        'case_context': 'Sudden nocturnal onset of severe great toe pain, elevated serum uric acid (8.9 mg/dL), touch-sensitive hyperesthesia, pulse reveals rapid Pitta-Rakta Gati.',
        'option_a': 'Sandhigata Vata',
        'option_b': 'Uttana Vatarakta (Gouty arthritis)',
        'option_c': 'Asthi Majja Kshaya',
        'option_d': 'Kroshtukasheersha',
        'correct_answer': 'B',
        'explanation': 'Sudden nocturnal onset of acute burning pain and swelling at the Padangushtha (great toe) triggered by alcohol/Lavana-Amla diet is classical Uttana Vatarakta.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'Which classical clinical posture provides symptomatic relief in a patient experiencing an acute episode of Tamaka Shwasa (Bronchial Asthma)?',
        'question_type': 'mcq',
        'option_a': 'Supine recumbent posture (lying flat on back)',
        'option_b': 'Aseeno Labhate Saukhyam (Sitting upright / leaning forward)',
        'option_c': 'Prone position (lying on abdomen)',
        'option_d': 'Left lateral decubitus posture',
        'correct_answer': 'B',
        'explanation': 'Charaka notes "Aseeno Labhate Saukhyam, Shayane Shvasa Peedita"—patients with Tamaka Shwasa find relief in sitting upright as recumbency aggravates airway obstruction.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'When inspecting a patient with abdominal distension (Udara Roga), which physical sign distinguishes Jalodara (Ascites) from Vatodara (Tympanites)?',
        'question_type': 'mcq',
        'option_a': 'Presence of fluid thrill (wave) and shifting dullness on percussion in Jalodara, versus tympanitic drum-like resonance in Vatodara',
        'option_b': 'Vatodara always presents with jaundice and scleral icterus',
        'option_c': 'Jalodara abdomen feels rigid like a wooden plank without any fluid movement',
        'option_d': 'Vatodara exhibits prominent venous engorgement around the umbilicus exclusively',
        'correct_answer': 'A',
        'explanation': 'Jalodara is confirmed by fluid wave (Dravasanchiti) and shifting dullness, whereas Vatodara produces hollow tympanitic resonance due to trapped gas.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'During Ashtavidha Pariksha, which anatomical location is canonically examined under Sparsha Pariksha for detecting visceral temperature and unctuousness?',
        'question_type': 'mcq',
        'option_a': 'Sole of foot only',
        'option_b': 'Skin temperature, texture (Sheeta, Ushna, Snigdha, Ruksha), and abdominal palpation',
        'option_c': 'Hair shaft thickness',
        'option_d': 'Pupillary constriction speed',
        'correct_answer': 'B',
        'explanation': 'Sparsha Pariksha evaluates skin tactile sensations (temperature, dryness, sweat, edema, and localized heat).',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Clinical Skills',
        'question_text': 'What type of radial pulse movement is canonically perceived in a patient suffering from chronic Sannipataja Jwara (mixed tridoshic septic condition)?',
        'question_type': 'mcq',
        'option_a': 'Pure Hamsa Gati',
        'option_b': 'Muhuscha Mandam Muhurasu Vegam (Erratic, alternating between slow and rapid jumping, occasionally disappearing)',
        'option_c': 'Steady unbroken slow pulse like an elephant',
        'option_d': 'Regular rhythmic bouncing pulse',
        'correct_answer': 'B',
        'explanation': 'In Sannipataja state, Nadi Gati is described as erratic, changing constantly from rapid to feeble or imperceptible.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },

    # =========================================================================
    # 3. PANCHAKARMA (10 Questions)
    # =========================================================================
    {
        'skill': 'Panchakarma',
        'question_text': 'Which of the following is considered a classical sign of optimum internal oleation (Samyak Snigdha Lakshana) prior to administering Vamana Karma?',
        'question_type': 'mcq',
        'option_a': 'Severe constipation and dry mouth',
        'option_b': 'Vatanulomana, Deeptagni (keen appetite), Snigdha Purisha (unctuous feces), and Snehodvega (aversion to ghee)',
        'option_c': 'Profuse sweating with elevated body temperature',
        'option_d': 'Hyperacidity and intense burning sensation',
        'correct_answer': 'B',
        'explanation': 'Samyak Snigdha Lakshanas described in Charaka Samhita include Vatanulomana, Deeptagni, soft unctuous stools containing unabsorbed fat, and Snehodvega.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'In the post-Panchakarma dietary protocol (Samsarjana Krama), what is the correct chronological sequence of dietary forms served to gradually rekindle the digestive fire?',
        'question_type': 'mcq',
        'option_a': 'Mamsa Rasa -> Krita Yusha -> Vilepi -> Peya',
        'option_b': 'Peya (thin gruel) -> Vilepi (thick gruel) -> Akrita Yusha -> Krita Yusha (seasoned soup) -> Mamsa Rasa',
        'option_c': 'Takra -> Peya -> Odana -> Mamsa Rasa',
        'option_d': 'Yavagu -> Ksheera -> Peya -> Vilepi',
        'correct_answer': 'B',
        'explanation': 'Samsarjana Krama sequentially transitions from lightest Peya to Vilepi, then unseasoned Yusha, seasoned Yusha, and finally Mamsa Rasa / normal diet.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'Which therapeutic enema is administered in a standard small dosage (typically 1.5 to 2 Pala / ~72-96 ml) immediately after food, requires no strict fasting, and can be given daily safely in Vata disorders?',
        'question_type': 'mcq',
        'option_a': 'Niruha Basti',
        'option_b': 'Kashaya Basti',
        'option_c': 'Matra Basti',
        'option_d': 'Uttara Basti',
        'correct_answer': 'C',
        'explanation': 'Matra Basti is a subtype of Anuvasana Basti given in small volume, free from strict dietary complications, nourishing tissues and pacifying Vata.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'During Virechana Karma, what physiological observation marks the completion of the procedure and indicates optimum elimination (Antiki Shuddhi)?',
        'question_type': 'mcq',
        'option_a': 'Vatanta (cessation with flatulence)',
        'option_b': 'Pittanta (cessation with yellow bile)',
        'option_c': 'Kaphanta (cessation with mucus / phlegm emergence at the end)',
        'option_d': 'Raktanta (cessation with blood discharge)',
        'correct_answer': 'C',
        'explanation': 'Virechana canonically eliminates Mala first, followed by Pitta, and finishes when Kapha (mucus) emerges (Kaphanta Shuddhi).',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'During therapeutic emesis (Vamana Karma), what is the classical observation indicating optimum outcome (Antiki Shuddhi)?',
        'question_type': 'mcq',
        'option_a': 'Kaphanta Shuddhi',
        'option_b': 'Pittanta Shuddhi (vomiting ends with bile emergence)',
        'option_c': 'Vatanta Shuddhi',
        'option_d': 'Pure water emergence only',
        'correct_answer': 'B',
        'explanation': 'In Vamana Karma, Kapha is eliminated first, and the procedure is completed when Pitta (yellowish bile) emerges (Pittanta Shuddhi).',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'Which subtype of Nasya Karma involves administering just two drops of medicated oil (like Anu Taila) in each nostril daily for preventive and rejuvenating health?',
        'question_type': 'mcq',
        'option_a': 'Marsha Nasya',
        'option_b': 'Pratimarsha Nasya',
        'option_c': 'Pradhamana Nasya',
        'option_d': 'Avapeedaka Nasya',
        'correct_answer': 'B',
        'explanation': 'Pratimarsha Nasya consists of 2 drops in each nostril, safe for daily use throughout life from childhood to old age without strict seasonal restrictions.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'In the classical protocol of Niruha Basti preparation (Basti Kalpana), in what exact sequence must the ingredients be blended into a homogenous emulsion?',
        'question_type': 'mcq',
        'option_a': 'Decoction -> Paste -> Ghee -> Honey -> Salt',
        'option_b': 'Madhu (Honey) -> Saindhava (Salt) -> Sneha (Medicated Oil/Ghee) -> Kalka (Herb paste) -> Kwatha (Decoction)',
        'option_c': 'Kwatha -> Sneha -> Kalka -> Madhu -> Saindhava',
        'option_d': 'Saindhava -> Kwatha -> Sneha -> Madhu -> Kalka',
        'correct_answer': 'B',
        'explanation': 'Classical sequence for Niruha Basti: First Madhu + Saindhava are thoroughly mixed, then Sneha is incorporated, followed by fine Kalka, and lastly warm Kwatha is added to form a stable emulsion.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'A patient suffering from localized lumbar spondylosis (Kati Shula) is prescribed Kati Basti. What medicated taila is canonically indicated for Vata-Kapha pacification and relieving neuro-muscular stiffness?',
        'question_type': 'case_study',
        'case_context': '54-year-old male with chronic L4-L5 disc bulge, morning stiffness, radiation down the posterior thigh, cold numbness in left calf.',
        'option_a': 'Chandanadi Taila',
        'option_b': 'Mahanarayana Taila / Kottamchukkadi Taila',
        'option_c': 'Kumkumadi Taila',
        'option_d': 'Neelibhringadi Taila',
        'correct_answer': 'B',
        'explanation': 'Mahanarayana Taila and Kottamchukkadi Taila possess potent Vata-Kaphahara, Shulaghna, and Snigdha-Ushna properties ideal for Kati Basti in lumbar spondylosis.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'Which of the following conditions is an absolute contraindication (Varjya) for administering classical Raktamokshana (Bloodletting therapy)?',
        'question_type': 'mcq',
        'option_a': 'Dushta Vrana (infected ulcer)',
        'option_b': 'Severe Pandu (severe anemia / hemoglobin < 7 g/dL) and Garbhini (pregnancy)',
        'option_c': 'Vatarakta with severe burning',
        'option_d': 'Localized Vidradhi (abscess)',
        'correct_answer': 'B',
        'explanation': 'Raktamokshana is contraindicated in severe Pandu, pregnant women, emaciated patients (Krisha), generalized edema (Sarvanga Shotha), and bleeding disorders.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Panchakarma',
        'question_text': 'During classical Shirodhara therapy for severe insomnia (Anidra) and anxiety, what is the optimum stream height and oil temperature standard?',
        'question_type': 'mcq',
        'option_a': 'Stream height of 4 Angula (~3-4 inches) above forehead, maintaining lukewarm temperature (~38-40°C) with continuous rhythmic oscillation',
        'option_b': 'Ice cold oil poured from 2 feet height',
        'option_c': 'Boiling hot oil poured at single static point',
        'option_d': 'Rapid intermittent splashing of water from 1 meter distance',
        'correct_answer': 'A',
        'explanation': 'Shirodhara protocol requires lukewarm oil poured in a continuous rhythmic stream from approximately 4 Angula (3-4 inches) height across the forehead.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },

    # =========================================================================
    # 4. KAYACHIKITSA (10 Questions)
    # =========================================================================
    {
        'skill': 'Kayachikitsa',
        'question_text': 'Which diagnostic criterion most reliably distinguishes Amavata (Rheumatoid presentation) from Sandhigata Vata (Osteoarthritis)?',
        'question_type': 'mcq',
        'option_a': 'Amavata presents with morning stiffness, shifting polyarthritis, Angamarda, and relief after Langhana/Svedana',
        'option_b': 'Sandhigata Vata occurs predominantly in young females with high fever',
        'option_c': 'Amavata responds best to immediate heavy unctuous Snehana Basti',
        'option_d': 'Sandhigata Vata exhibits elevated systemic ESR and severe thirst',
        'correct_answer': 'A',
        'explanation': 'Amavata is an Ama-predominant systemic disease with shifting joint pain, stiffness, and positive response to Langhana and Ruksha Sveda, unlike degenerative Sandhigata Vata.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'A 50-year-old patient with newly detected Prameha presents with turbid urine, fatigue, polydipsia, and excessive sleepiness. The patient is Sthula (obese) with robust physical strength. What is the fundamental Chikitsa principle?',
        'question_type': 'case_study',
        'case_context': '50-year-old executive, sedentary lifestyle, BMI 31, fasting blood sugar 160 mg/dL, heavy coated tongue, complains of sweetish taste in mouth.',
        'option_a': 'Santarpana (Nourishing) therapy with heavy milk and ghee diet',
        'option_b': 'Apatarpana (Depleting) therapy with Tikta-Kashaya-Katu Dravyas, Shodhana, and regular physical exercise',
        'option_c': 'Brimhana Rasayana with Ashwagandha and Ksheerabala',
        'option_d': 'Immediate complete fasting for 30 consecutive days',
        'correct_answer': 'B',
        'explanation': 'In Sthula Pramehi with adequate strength, Apatarpana (Shodhana followed by Medohara, Kaphahara drugs like Shilajatu, Asanadi Kwatha, and exercise) is the indicated Chikitsa.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'Which classical herbomineral formulation containing Katuki, Triphala, Chitramoola, Guggulu, and purified metals is the drug of choice in Hepato-biliary disorders and deep-seated Kapha-Meda obstruction?',
        'question_type': 'mcq',
        'option_a': 'Sudarshana Churna',
        'option_b': 'Arogyavardhini Vati',
        'option_c': 'Sutashekhara Rasa',
        'option_d': 'Chitrakadi Vati',
        'correct_answer': 'B',
        'explanation': 'Arogyavardhini Vati stimulates Pittasarana, resolves Yakrit-Pleeha enlargement, clears Mala and Medas, and kindles Dhatvagni.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'A 28-year-old software engineer presents with alternate episodes of constipation and watery loose stools (Muhurbaddha Muhurdrava), abdominal gurgling, and passage of undigested food particles after eating. What is the diagnosis and prime therapeutic diet?',
        'question_type': 'case_study',
        'case_context': '28-year-old male, chronic irregular digestion for 6 months following stress and fast foods, lost 4 kg weight, tongue lightly coated, appetite poor.',
        'option_a': 'Grahani Roga treated with Takra (Buttermilk) and Deepana-Pachana drugs',
        'option_b': 'Atisara treated with immediate Snehana and heavy milk diet',
        'option_c': 'Arsha treated with surgical excision',
        'option_d': 'Jwara treated with cold iced drinks',
        'correct_answer': 'A',
        'explanation': 'Muhurbaddha Muhurdrava (alternating constipation and diarrhea) and undigested stools are cardinal features of Grahani Roga, for which Takra is celebrated as nectar.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'Which classical formulation is the primary line of treatment in Vidagdha Jeerna and Amlapitta characterized by sour eructations, retrosternal burning, and hyperacidity?',
        'question_type': 'mcq',
        'option_a': 'Avipattikar Churna / Kamadudha Rasa',
        'option_b': 'Trikatu Churna',
        'option_c': 'Chitrakadi Vati in hot water',
        'option_d': 'Kanakasava',
        'correct_answer': 'A',
        'explanation': 'Avipattikar Churna (with Trivrit for mild Anulomana) and Kamadudha Rasa pacify aggravated Pachaka Pitta and eliminate acidic metabolic wastes.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'What is the prime herbal drug of choice canonically indicated in Hridroga (cardiac disorders) that possesses Kashaya-Tikta Rasa, Sheeta Virya, and Hridya cardio-protective properties?',
        'question_type': 'mcq',
        'option_a': 'Arjuna (Terminalia arjuna)',
        'option_b': 'Bhallataka (Semecarpus anacardium)',
        'option_c': 'Vatsanabha (Aconitum ferox)',
        'option_d': 'Kupilu (Strychnos nux-vomica)',
        'correct_answer': 'A',
        'explanation': 'Arjuna bark is the premier Hridya Rasayana in Ayurveda, supporting cardiac contractility and strengthening the myocardium.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'In the clinical management of Shakhashrita Kamala (Obstructive Jaundice), what is the hallmark clinical sign reflecting obstruction of bile flow into the gut?',
        'question_type': 'mcq',
        'option_a': 'Shweta / Tila-pishta-nibha Purisha (Clay-colored / white stools) with deep yellow urine',
        'option_b': 'Dark black tarry stools',
        'option_c': 'Bright red rectal bleeding',
        'option_d': 'Green watery frothy diarrhea',
        'correct_answer': 'A',
        'explanation': 'Shakhashrita Kamala presents with clay-colored/white stools (Tila-pishta-nibha) because bile (Pitta) is blocked from entering the gastrointestinal tract and diverted to tissues.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'Which classical Chikitsa Sutra is indicated for managing Medoroga (Obesity and metabolic syndrome) according to Charaka?',
        'question_type': 'mcq',
        'option_a': 'Guru cha Atarpana (Heavy in quality but non-nourishing / low-calorie food items like Yava, Mudga, Madhu, and Guggulu)',
        'option_b': 'Laghu and Santarpana heavy sweet diets',
        'option_c': 'Complete rest with excessive daytime sleep',
        'option_d': 'High-fat animal meat soups',
        'correct_answer': 'A',
        'explanation': 'Charaka dictates "Guru cha Atarpana Cheshthitam Medoghnanam"—foods that are bulky and satisfying (Guru) to quieten Tikshnagni but depleting (Atarpana) in calories like barley (Yava).',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'In the treatment of acute Vataja Shula (colicky spasmodic pain), which immediate simple intervention provides instantaneous relief by pacifying Vata?',
        'question_type': 'mcq',
        'option_a': 'Ushna Sveda (warm fomentation) and administration of Hingwashtaka Churna with warm ghee',
        'option_b': 'Ice pack application to abdomen',
        'option_c': 'Drinking large volumes of cold milk',
        'option_d': 'Vigorous physical running exercise',
        'correct_answer': 'A',
        'explanation': 'Vataja Shula is pacified rapidly by Ushna and Snigdha therapies (warm fomentation and Dipana-Anulomana herbs with Ghruta).',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Kayachikitsa',
        'question_text': 'In the classical staging of Jwara (Fever), what therapeutic principle must be strictly applied during the initial stage of Navajwara (first 7 days of acute fever)?',
        'question_type': 'mcq',
        'option_a': 'Langhana (Fasting/light diet), Swedana, and Shadangodaka intake; avoiding heavy medicines and unctuous foods',
        'option_b': 'Immediate administration of heavy Bhasmas and Snehana Basti',
        'option_c': 'Heavy meat soups and ice cold baths',
        'option_d': 'Virechana Karma on day 1 of acute fever',
        'correct_answer': 'A',
        'explanation': 'In Navajwara, Langhana is premier ("Jwaradau Langhanam Proktam") to digest circulating Ama, avoiding early Snehana or heavy therapeutics which worsen the disease.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },

    # =========================================================================
    # 5. DRAVYAGUNA (10 Questions)
    # =========================================================================
    {
        'skill': 'Dravyaguna',
        'question_text': 'What is the classical Rasa Panchaka profile of Ashwagandha (Withania somnifera Dunal)?',
        'question_type': 'mcq',
        'option_a': 'Madhura-Amla Rasa, Sheeta Virya, Madhura Vipaka, Pittahara',
        'option_b': 'Tikta-Kashaya-Madhura Rasa, Ushna Virya, Madhura Vipaka, Vata-Kaphahara and Balya',
        'option_c': 'Katu-Tikta Rasa, Sheeta Virya, Katu Vipaka, Vatakopaka',
        'option_d': 'Lavana-Kashaya Rasa, Ushna Virya, Amla Vipaka, Pittavardhaka',
        'correct_answer': 'B',
        'explanation': 'Ashwagandha has Tikta, Kashaya, Madhura Rasa, Ushna Virya, and Madhura Vipaka, making it a premier Rasayana, Balya, and Vata-Kapha pacifier.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'According to the classical concept of Ritu Haritaki, which Anupana is canonically advised for administering Haritaki during Varsha Ritu (Monsoon season)?',
        'question_type': 'mcq',
        'option_a': 'Sharkara (Cane sugar)',
        'option_b': 'Saindhava Lavana (Rock salt)',
        'option_c': 'Shunti (Dry ginger powder)',
        'option_d': 'Madhu (Honey)',
        'correct_answer': 'B',
        'explanation': 'In Varsha Ritu, Haritaki is taken with Saindhava Lavana to prevent Vata accumulation caused by cold and damp environmental conditions.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'Which pharmacognostical analytical test is used to detect the presence of extraneous earthy and siliceous inorganic contamination in raw herbal powders?',
        'question_type': 'mcq',
        'option_a': 'Alcohol-Soluble Extractive value',
        'option_b': 'Acid-Insoluble Ash value',
        'option_c': 'Moisture Content (Loss on Drying)',
        'option_d': 'Swelling Index',
        'correct_answer': 'B',
        'explanation': 'Acid-Insoluble Ash measures silica, sand, and earthy matter that does not dissolve in dilute hydrochloric acid, serving as a critical purity index.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'What is the primary pharmacological action (Karma) of Guduchi (Tinospora cordifolia) on Tridosha and Agni?',
        'question_type': 'mcq',
        'option_a': 'Tridoshahara, Deepana, Pachana, Rasayana, and Jwaraghna',
        'option_b': 'Pure Kapha Vardhaka and Vamana Karaka',
        'option_c': 'Teekshna Virechaka and Pittavardhaka',
        'option_d': 'Ruksha Grahi without any Deepana action',
        'correct_answer': 'A',
        'explanation': 'Guduchi is unique in being Tridoshahara (balancing all three Doshas), Medhya, Deepana, Jwaraghna, and an immunomodulatory Rasayana.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'What are the three canonical herbal constituents of classical Triphala Churna and their standard botanical proportions according to the Ayurvedic Pharmacopoeia of India?',
        'question_type': 'mcq',
        'option_a': 'Haritaki, Bibhitaki, and Amalaki in equal parts (1:1:1)',
        'option_b': 'Shunti, Maricha, Pippali in 1:2:3',
        'option_c': 'Guduchi, Gokshura, Amalaki in equal parts',
        'option_d': 'Nimba, Patola, Katuki in 2:1:1',
        'correct_answer': 'A',
        'explanation': 'Triphala comprises pericarp powders of Haritaki (Terminalia chebula), Bibhitaki (Terminalia bellirica), and Amalaki (Phyllanthus emblica) in equal proportions (1:1:1).',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'Which classical Shodhana (purification) medium is canonically utilized for purifying raw Guggulu (Commiphora mukul) to remove physical impurities and reduce gastric irritation?',
        'question_type': 'mcq',
        'option_a': 'Triphala Kwatha / Godugdha (Cow milk) decoction via Dola Yantra',
        'option_b': 'Distilled petroleum ether boiling',
        'option_c': 'Cold dilute sulphuric acid wash',
        'option_d': 'Pure alcohol reflux exclusively',
        'correct_answer': 'A',
        'explanation': 'Raw Guggulu is purified by boiling in Triphala Kwatha or Godugdha through Dola Yantra, then filtered and dried into Shuddha Guggulu.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'What is the prime therapeutic indication and pharmacological action (Karma) of Shatavari (Asparagus racemosus)?',
        'question_type': 'mcq',
        'option_a': 'Stanya Janana (galactagogue), Shukrala, Medhya, Pitta-Vata Shamaka, and female reproductive Rasayana',
        'option_b': 'Teekshna Lekhana for severe obesity exclusively',
        'option_c': 'Pure Vamana Karaka in Kapha disorders',
        'option_d': 'Severe Ruksha Malasangrahaniya',
        'correct_answer': 'A',
        'explanation': 'Shatavari has Madhura-Tikta Rasa, Sheeta Virya, and Madhura Vipaka, functioning as premier Stanya Janana, Balya, and Pittahara Rasayana.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'Which active phytochemical biomarker is quantified via High-Performance Thin-Layer Chromatography (HPTLC) for standardization of Haridra (Curcuma longa) rhizome extracts?',
        'question_type': 'mcq',
        'option_a': 'Curcumin (Curcuminoids)',
        'option_b': 'Withaferin A',
        'option_c': 'Guggulsterone E & Z',
        'option_d': 'Gymnemic acid',
        'correct_answer': 'A',
        'explanation': 'Curcumin (and total curcuminoids) is the primary bioactive marker used for analytical standardization of Haridra.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'In the classical administration of Vardhamana Pippali Rasayana, how is the dosage of Pippali fruits sequentially titrated for respiratory and metabolic disorders?',
        'question_type': 'mcq',
        'option_a': 'Started at a small dose (e.g. 3-5 fruits), increased by fixed increment daily up to a peak (e.g. 10 days), and then gradually tapered down in reverse sequence',
        'option_b': '100 fruits taken all at once on day 1 only',
        'option_c': 'Fixed 1 fruit taken daily for 10 years without change',
        'option_d': 'Random dosage varying every hour',
        'correct_answer': 'A',
        'explanation': 'Vardhamana Rasayana is a classic titration protocol where dosage increases day-by-day to a peak and then descends gradually, allowing the body to safely adapt to Deepana-Rasayana effects.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Dravyaguna',
        'question_text': 'What classical Karma is exhibited by Bhringaraja (Eclipta prostrata) that makes it prominent in both hair care (Keshya) and liver care (Yakrit-Pleehahara)?',
        'question_type': 'mcq',
        'option_a': 'Katu-Tikta Rasa, Ushna Virya, Keshya, Rasayana, and Yakrit-uttejaka',
        'option_b': 'Heavy Madhura, Sheeta Virya causing extreme lethargy',
        'option_c': 'Purely corrosive Kshariya action',
        'option_d': 'Vata-Prakopaka and toxic emetic',
        'correct_answer': 'A',
        'explanation': 'Bhringaraja is Tikta-Katu in Rasa and Ushna in Virya, possessing Keshya, Rasayana, and hepatoprotective properties.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },

    # =========================================================================
    # 6. RESEARCH METHODOLOGY (10 Questions)
    # =========================================================================
    {
        'skill': 'Research Methodology',
        'question_text': 'What defines the "Reverse Pharmacology" paradigm pioneered in Ayurvedic scientific research?',
        'question_type': 'mcq',
        'option_a': 'Synthesizing chemical analogues in a test tube before testing on animal models',
        'option_b': 'Starting from documented bedside clinical experience and historical Ayurvedic evidence to guide laboratory drug discovery and mechanism validation',
        'option_c': 'Conducting Phase IV post-marketing surveillance exclusively',
        'option_d': 'Randomly screening synthetic chemical libraries against recombinant enzymes',
        'correct_answer': 'B',
        'explanation': 'Reverse Pharmacology in Ayurveda utilizes centuries of documented clinical use as the starting point ("bedside to bench"), accelerating safe translational validation.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'In a randomized controlled trial comparing an Ayurvedic polyherbal formulation with an active standard drug for osteoarthritis, the statistical analysis reports p = 0.004. How should this result be scientifically interpreted?',
        'question_type': 'mcq',
        'option_a': 'The trial failed to achieve scientific validity',
        'option_b': 'There is statistically significant evidence (p < 0.01) of a therapeutic difference, with less than 0.4% likelihood of occurring by random chance alone',
        'option_c': 'The sample size was definitively insufficient',
        'option_d': 'The formulation is completely inactive',
        'correct_answer': 'B',
        'explanation': 'A p-value less than the standard threshold of 0.05 indicates statistical significance, rejecting the null hypothesis with high confidence.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'According to Good Clinical Practice (GCP) guidelines for AYUSH trials, which ethical body must review and grant mandatory approval prior to enrolling human participants?',
        'question_type': 'mcq',
        'option_a': 'Local Municipal Corporation',
        'option_b': 'Institutional Ethics Committee (IEC) / Institutional Review Board (IRB)',
        'option_c': 'Commercial Marketing Department',
        'option_d': 'Pharmacy Retailers Association',
        'correct_answer': 'B',
        'explanation': 'Every clinical study on human participants requires prior ethical approval from an accredited Institutional Ethics Committee to ensure participant safety and rights.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'Which national clinical trial registry portal in India is mandatory for prospectively registering all biomedical and AYUSH clinical trials before enrolling the first participant?',
        'question_type': 'mcq',
        'option_a': 'Clinical Trials Registry - India (CTRI)',
        'option_b': 'Wikipedia Health Portal',
        'option_c': 'National Highway Authority database',
        'option_d': 'Income Tax filing portal',
        'correct_answer': 'A',
        'explanation': 'CTRI (ctri.icmr.org.in) hosted by ICMR-NIMS is the mandatory registry for all clinical trials conducted in India.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'Which international reporting standard provides formal guidelines and an extension checklist for transparently reporting Randomized Controlled Trials evaluating Herbal Interventions and Traditional Medicine?',
        'question_type': 'mcq',
        'option_a': 'CONSORT Extension for Herbal Interventions',
        'option_b': 'GAAP Accounting Standards',
        'option_c': 'IEEE Wireless Protocol',
        'option_d': 'ISO 9001 quality manual',
        'correct_answer': 'A',
        'explanation': 'The CONSORT extension for Herbal Interventions specifies reporting requirements for herbal product names, extraction methods, standardization, and batch details in clinical trial publications.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'In designing a double-blind clinical trial for a classical Ayurvedic Decoction (Kwatha), why is blinding uniquely challenging, and what method resolves it?',
        'question_type': 'case_study',
        'case_context': 'Clinical trial evaluating Dashamoola Kwatha vs Placebo in cervical spondylosis. The distinctive herbal taste, aroma, and dark color can easily unblind patients and clinicians.',
        'option_a': 'Blinding cannot be performed and must be abandoned completely',
        'option_b': 'Encapsulating lyophilized standardized dry extracts or using matched color-flavor vehicle placebos to ensure indistinguishable appearance and taste',
        'option_c': 'Telling patients the formulation name before each dose',
        'option_d': 'Testing on animals without blinding',
        'correct_answer': 'B',
        'explanation': 'Lyophilization into encapsulated dry extracts or formulation matching allows effective blinding for organoleptically distinct Ayurvedic decoctions.',
        'difficulty': 'Hard',
        'marks': 2.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'When calculating the required sample size for an interventional clinical trial, which statistical parameters are fundamentally required?',
        'question_type': 'mcq',
        'option_a': 'Type I error rate (alpha, typically 0.05), Statistical Power (1-beta, typically 80-90%), expected effect size, and standard deviation',
        'option_b': 'Total hospital bed capacity only',
        'option_c': 'The number of doctors working in the department',
        'option_d': 'The price of raw herbs per kilogram',
        'correct_answer': 'A',
        'explanation': 'Scientific sample size calculation requires pre-specifying alpha error, statistical power, expected clinically meaningful effect size, and outcome variance.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'Which research study design provides the highest level of epidemiological evidence for determining the therapeutic efficacy of a newly standardized Ayurvedic formulation?',
        'question_type': 'mcq',
        'option_a': 'Systematic Review and Meta-Analysis of double-blind Randomized Controlled Trials (RCTs)',
        'option_b': 'Single anecdotal case report in a local magazine',
        'option_c': 'Cross-sectional survey of 10 people',
        'option_d': 'Uncontrolled retrospective patient diary',
        'correct_answer': 'A',
        'explanation': 'In the hierarchy of evidence-based medicine, Systematic Reviews and Meta-Analyses of well-conducted RCTs occupy the pinnacle of clinical evidence.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'What is the primary objective of Phase I clinical trials in the drug development pipeline for new herbomineral formulations?',
        'question_type': 'mcq',
        'option_a': 'Assessing safety, tolerability, pharmacokinetics, and maximum tolerated dose in a small cohort of healthy human volunteers',
        'option_b': 'Establishing retail commercial pricing',
        'option_c': 'Comparing with 10 competitors across 10,000 patients',
        'option_d': 'Advertising the drug on national television',
        'correct_answer': 'A',
        'explanation': 'Phase I trials focus primarily on safety, bioavailability, and dose tolerance in humans after preclinical toxicity testing.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Research Methodology',
        'question_text': 'Which guideline checklist must be followed when conducting and reporting Systematic Reviews and Meta-Analyses in medical literature?',
        'question_type': 'mcq',
        'option_a': 'PRISMA (Preferred Reporting Items for Systematic Reviews and Meta-Analyses)',
        'option_b': 'STARD Guidelines for diagnostic accuracy only',
        'option_c': 'GANTT chart template',
        'option_d': 'SWOT Analysis framework',
        'correct_answer': 'A',
        'explanation': 'PRISMA statement provides evidence-based minimum items for reporting in systematic reviews and meta-analyses.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },

    # =========================================================================
    # 7. DOCUMENTATION (10 Questions)
    # =========================================================================
    {
        'skill': 'Documentation',
        'question_text': 'Under NABH AYUSH Hospital Accreditation Standards, what is the mandatory timeframe within which an initial medical and nursing assessment must be documented for a newly admitted IPD patient?',
        'question_type': 'mcq',
        'option_a': 'Within 24 hours of admission',
        'option_b': 'Within 7 days of admission',
        'option_c': 'Only at the time of discharge',
        'option_d': 'After completion of all diagnostic lab tests',
        'correct_answer': 'A',
        'explanation': 'NABH standards mandate comprehensive initial clinical assessment within 24 hours of hospital admission to ensure timely, structured inpatient care planning.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'Which globally recognized reporting guideline provides a structured 13-item checklist specifically designed for publishing comprehensive clinical case reports in medical journals?',
        'question_type': 'mcq',
        'option_a': 'CONSORT Statement',
        'option_b': 'CARE Guidelines (CAse REport guidelines)',
        'option_c': 'PRISMA Guidelines',
        'option_d': 'STROBE Statement',
        'correct_answer': 'B',
        'explanation': 'The CARE guidelines provide an international consensus-based framework for writing transparent, rigorous, and high-impact clinical case reports.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'What is the primary regulatory purpose of maintaining Batch Manufacturing Records (BMR) and Standard Operating Procedures (SOP) in an Ayurvedic pharmacy?',
        'question_type': 'mcq',
        'option_a': 'Ensuring marketing promotional visibility',
        'option_b': 'Ensuring traceability, GMP compliance, safety, and batch-to-batch consistency of formulations',
        'option_c': 'Calculating retail profit margins exclusively',
        'option_d': 'Eliminating the need for raw material testing',
        'correct_answer': 'B',
        'explanation': 'BMR and SOP documentation are foundational for GMP compliance, ensuring that every batch meets rigorous quality, safety, and reproducibility benchmarks.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'Under the National Pharmacovigilance Programme for AYUSH, what documentation protocol must be initiated when an unexpected Adverse Drug Reaction (ADR) is observed following an Ayurvedic formulation?',
        'question_type': 'mcq',
        'option_a': 'Complete the standardized AYUSH ADR Reporting Form with patient details, suspect drug details, onset latency, and clinical outcome, submitting to the regional pharmacovigilance center',
        'option_b': 'Conceal the event and destroy all patient case sheets immediately',
        'option_c': 'Publish an anonymous complaint on social media',
        'option_d': 'Stop all patient treatments without recording anything',
        'correct_answer': 'A',
        'explanation': 'Pharmacovigilance mandates filling out the official AYUSH ADR reporting form to document adverse events for regulatory review and drug safety monitoring.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'What essential legal and clinical components must be documented in an Informed Consent form prior to performing specialized procedures like Ksharasutra or Agnikarma?',
        'question_type': 'mcq',
        'option_a': 'Explanation of procedure in patient vernacular language, potential risks, expected clinical outcomes, alternative treatments, voluntary consent signature, and doctor credentials',
        'option_b': 'Patient bank account details only',
        'option_c': 'A verbal handshake with no written record',
        'option_d': 'Signature of a distant relative without patient awareness',
        'correct_answer': 'A',
        'explanation': 'Informed consent is a medico-legal requirement requiring documented explanation of the procedure, risks, alternatives, and voluntary signed consent.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'What mandatory clinical details must be included in a formal Inpatient Discharge Summary in an accredited Ayurvedic hospital?',
        'question_type': 'mcq',
        'option_a': 'Admission and discharge diagnosis, summary of clinical course, Panchakarma procedures performed with dates, discharge medications with dosage/Anupana, Pathya-Apathya instructions, and follow-up date',
        'option_b': 'Billing receipt only without clinical diagnosis',
        'option_c': 'Doctor signature on a blank sheet',
        'option_d': 'Copy of hospital cafeteria menu',
        'correct_answer': 'A',
        'explanation': 'Discharge summaries must clearly communicate the complete diagnosis, interventions, take-home prescriptions, dietary regimen, and scheduled review.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'According to statutory medical council regulations, what is the minimum required retention period for inpatient medical case records (IPD records) in hospitals?',
        'question_type': 'mcq',
        'option_a': 'At least 3 years from the date of commencement of treatment / discharge',
        'option_b': 'Only 24 hours',
        'option_c': 'No record keeping is necessary',
        'option_d': '1 month only',
        'correct_answer': 'A',
        'explanation': 'Medical records regulations stipulate that inpatient records must be retained for at least 3 years to ensure legal accountability and continuity of care.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'When writing an Ayurvedic medical prescription, what standard elements ensure clinical safety and legal validity?',
        'question_type': 'mcq',
        'option_a': 'Patient demographic details, Doctor registration number, generic botanical/classical formulation names, precise dosage, specific Anupana, administration timing (Kala), duration, and sign-off',
        'option_b': 'Brand name only without dosage or duration',
        'option_c': 'Unsigned slip with illegible abbreviations',
        'option_d': 'Verbal instructions without written prescription',
        'correct_answer': 'A',
        'explanation': 'Prescriptions must be legible, unambiguous, state registration credentials, and specify dosage with classical Anupana and Aushadha Sevana Kala.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'What documentation file in clinical research contains all essential trial records (ethics approvals, investigator brochure, signed consents, monitoring logs) allowing audit of study conduct?',
        'question_type': 'mcq',
        'option_a': 'Trial Master File (TMF)',
        'option_b': 'General hospital ledger',
        'option_c': 'Visitor guestbook',
        'option_d': 'Pharmacy retail counter book',
        'correct_answer': 'A',
        'explanation': 'The Trial Master File (TMF) holds all critical regulatory and operational documents required for GCP inspection and audit.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Documentation',
        'question_text': 'Under Schedule T of the Drugs and Cosmetics Act 1940, what documentation is legally mandated for validating raw herbal authentication in manufacturing units?',
        'question_type': 'mcq',
        'option_a': 'Certificate of Analysis (CoA) documenting botanical identity, foreign matter, moisture, ash values, and heavy metal/microbial limits',
        'option_b': 'Verbal assurance from local suppliers',
        'option_c': 'Transport toll receipt only',
        'option_d': 'Photograph of herb packaging box',
        'correct_answer': 'A',
        'explanation': 'Schedule T GMP mandates Certificate of Analysis for each raw material batch verifying pharmacopoeial quality standards prior to release for formulation.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },

    # =========================================================================
    # 8. COMMUNICATION (10 Questions)
    # =========================================================================
    {
        'skill': 'Communication',
        'question_text': 'A patient with chronic Amlapitta repeatedly fails to follow dietary advice because of erratic work travel schedules. What is the most effective physician-patient communication strategy?',
        'question_type': 'case_study',
        'case_context': '36-year-old software consultant with recurring sour reflux and burning sensation, eats late night spicy restaurant meals due to overseas team calls.',
        'option_a': 'Strictly reprimand the patient and refuse treatment until compliance is 100%',
        'option_b': 'Use collaborative motivational interviewing to identify realistic portable Pathya substitutes (e.g. roasted barley flour, coconut water, cooling thermoses) and negotiate meal timings',
        'option_c': 'Prescribe double dosage of medicines and advise ignoring dietary restrictions completely',
        'option_d': 'Refer the patient immediately to emergency surgery',
        'correct_answer': 'B',
        'explanation': 'Effective therapeutic communication in Ayurveda (Ahara Parikalpana) involves empathetic collaboration and practical, personalized lifestyle adaptations.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'When communicating the prognosis of an incurable but manageable degenerative condition (Yapya Roga), what represents best ethical clinical practice in Ayurveda?',
        'question_type': 'mcq',
        'option_a': 'Falsely guarantee permanent cure within two weeks to keep patient spirits high',
        'option_b': 'Clearly explain the Yapya nature of the disorder, emphasizing that consistent lifestyle, Pathya, and Rasayana support will maintain quality of life and arrest progression',
        'option_c': 'Inform the patient that all hope is lost and terminate consultation',
        'option_d': 'Withhold all prognostic information completely from the patient and family',
        'correct_answer': 'B',
        'explanation': 'Charaka emphasizes truthful yet compassionate communication in Yapya disorders, ensuring the patient understands that continuous care ensures disease stability.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'A patient undergoing Vamana Karma becomes anxious and fearful upon feeling initial nausea during the Vega emergence. How should the clinical team communicate?',
        'question_type': 'case_study',
        'case_context': 'First-time Panchakarma patient experiencing natural physiological urge to vomit after taking Madanaphala decoction, feeling panicked about losing control.',
        'option_a': 'Calmly reassure the patient that nausea is the expected, desired physiological sign of Kapha mobilization, guiding them to breathe rhythmically and yield naturally to the Vegas',
        'option_b': 'Scold the patient for getting scared',
        'option_c': 'Administer anti-emetic medications immediately to stop the procedure',
        'option_d': 'Leave the patient alone in the room',
        'correct_answer': 'A',
        'explanation': 'Supportive reassuring communication during Panchakarma Pradhana Karma is essential for reducing patient anxiety and facilitating smooth, uninhibited Vega expulsion.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'In an integrative hospital setting, when communicating with modern allopathic specialists regarding a co-managed diabetic patient, what is the best collaborative communication method?',
        'question_type': 'mcq',
        'option_a': 'Present clinical findings using standardized biomedical terminologies alongside classical Ayurvedic assessments, detailing herb-drug interaction profiles clearly',
        'option_b': 'Reject all allopathic lab reports and demand stopping all insulin immediately',
        'option_c': 'Avoid speaking with other physicians completely',
        'option_d': 'Use purely Sanskrit terminology without explanation',
        'correct_answer': 'A',
        'explanation': 'Effective integrative communication requires bridges between traditional paradigms and conventional diagnostics, ensuring patient safety and synergy.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'Which communication model structured around Situation, Background, Assessment, and Recommendation (SBAR) is widely adopted for urgent clinical handovers in hospitals?',
        'question_type': 'mcq',
        'option_a': 'SBAR Communication Framework',
        'option_b': 'Social media direct messaging',
        'option_c': 'Noticeboard sticky notes',
        'option_d': 'Informal hallway chat',
        'correct_answer': 'A',
        'explanation': 'SBAR provides a standardized, concise structure for communicating critical patient status during shift handovers and medical consultations.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'When conducting a community Swastha Vritta workshop on lifestyle prevention of metabolic disorders, what pedagogical approach ensures maximum retention among non-medical participants?',
        'question_type': 'mcq',
        'option_a': 'Using simple relatable analogies (e.g. comparing Agni to kitchen fire), interactive visual meal guides, and actionable daily routine (Dinacharya) checklists',
        'option_b': 'Reciting dense Sanskrit verses for 3 hours without translation',
        'option_c': 'Distributing complex biochemical molecular pathway charts only',
        'option_d': 'Showing graphic surgical videos to intimidate the audience',
        'correct_answer': 'A',
        'explanation': 'Public health communication succeeds when complex traditional principles are translated into intuitive daily habits and practical lifestyle actions.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'When counseling an elderly geriatric patient with multi-morbidity taking multiple medications, what communication technique prevents medication confusion and non-adherence?',
        'question_type': 'mcq',
        'option_a': 'Providing a clear pictorial daily schedule aligning medicine timings with meals/routines and using the "Teach-Back" method where the patient repeats the instructions',
        'option_b': 'Giving 15 separate medicine bottles without labels',
        'option_c': 'Assuming the patient will remember everything from memory',
        'option_d': 'Writing instructions only in complex medical Latin',
        'correct_answer': 'A',
        'explanation': 'Teach-Back methodology and pictorial dosing charts confirm patient understanding and drastically reduce medication errors in geriatric care.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'How should an Ayurvedic physician ethically respond when a patient presents with an online health rumor claiming that a commercial juice can cure chronic cancer in 3 days?',
        'question_type': 'mcq',
        'option_a': 'Empathetically acknowledge the patient hope, objectively explain the lack of scientific and Samhita evidence, and educate on validated comprehensive integrative oncology care',
        'option_b': 'Agree with the rumor and sell the juice at a markup',
        'option_c': 'Mock the patient publicly',
        'option_d': 'Encourage stopping all medical therapy to try the miracle juice',
        'correct_answer': 'A',
        'explanation': 'Ethical communication requires debunking misinformation with empathy and evidence, protecting patients from fraudulent health claims.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'What is the primary role of active listening in the initial Ayurvedic clinical consultation (Darshana, Sparshana, Prashna)?',
        'question_type': 'mcq',
        'option_a': 'Building therapeutic trust, understanding psycho-emotional triggers (Manasika Hetu), and uncovering subtle dietary and sleep patterns that cause disease',
        'option_b': 'Filling out administrative billing forms while ignoring patient speech',
        'option_c': 'Interrupting the patient every 5 seconds to speed up consultation',
        'option_d': 'Selling cosmetics during consultation',
        'correct_answer': 'A',
        'explanation': 'Prashna Pariksha combined with empathetic active listening reveals Manasika and Sharirika Hetus essential for precision Ayurvedic diagnosis.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Communication',
        'question_text': 'In delivering difficult news regarding a severe chronic illness, which established protocol (such as SPIKES: Setting, Perception, Invitation, Knowledge, Empathy, Strategy) guides compassionate disclosure?',
        'question_type': 'mcq',
        'option_a': 'SPIKES Protocol for breaking bad news',
        'option_b': 'Automated SMS broadcast',
        'option_c': 'Sending news through a third-party courier',
        'option_d': 'Posting diagnostic reports on social media',
        'correct_answer': 'A',
        'explanation': 'The SPIKES protocol is a globally validated 6-step framework for delivering sensitive medical diagnoses with clinical empathy.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },

    # =========================================================================
    # 9. DIGITAL SKILLS (10 Questions)
    # =========================================================================
    {
        'skill': 'Digital Skills',
        'question_text': 'What is the primary role of the National AYUSH Morbidity and Standardized Terminologies Electronic (NAMASTE) Portal developed by the Ministry of AYUSH?',
        'question_type': 'mcq',
        'option_a': 'Selling commercial Ayurvedic products online',
        'option_b': 'Standardizing Ayurvedic clinical terminologies, morbidity codes, and enabling dual-coding integration with WHO ICD-11 Chapter 26 (Traditional Medicine)',
        'option_c': 'Streaming devotional audio content',
        'option_d': 'Managing pharmacy wholesale logistics only',
        'correct_answer': 'B',
        'explanation': 'The NAMASTE portal provides standardized codes for Ayurvedic diseases and therapies, facilitating electronic data exchange and WHO ICD-11 dual coding.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'Under the Telemedicine Practice Guidelines for Registered AYUSH Medical Practitioners, what essential clinical standard must be maintained during tele-consultation records?',
        'question_type': 'mcq',
        'option_a': 'No record retention is required for remote consultations',
        'option_b': 'Digital records of patient identity, consent, clinical notes, prescribed AYUSH medications, and follow-up advice must be securely archived for the statutory period',
        'option_c': 'Only patient phone numbers need to be recorded',
        'option_d': 'Prescriptions must only be transmitted via unencrypted SMS without doctor credentials',
        'correct_answer': 'B',
        'explanation': 'Statutory guidelines require secure archiving of teleconsultation records, patient consent, and standardized prescriptions containing the RMP registration number.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'Which online research database hosted by the Ministry of AYUSH cataloging peer-reviewed biomedical publications and clinical trials across AYUSH systems serves as a premier research repository?',
        'question_type': 'mcq',
        'option_a': 'AYUSH Research Portal (ayushportal.nic.in)',
        'option_b': 'Commercial shopping catalogue',
        'option_c': 'General search engine image repository',
        'option_d': 'Online gaming portal',
        'correct_answer': 'A',
        'explanation': 'The AYUSH Research Portal provides indexed access to thousands of peer-reviewed clinical, preclinical, and pharmacological studies on Ayurveda.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'What is the function of DHARA (Digital Helpline for Ayurveda Research Articles), established by AVT Institute for Advanced Research?',
        'question_type': 'mcq',
        'option_a': 'A comprehensive online indexing and search database dedicated exclusively to published scientific research on Ayurveda',
        'option_b': 'A pharmacy retail billing app',
        'option_c': 'A ticket booking platform',
        'option_d': 'A hospital cafeteria inventory tracker',
        'correct_answer': 'A',
        'explanation': 'DHARA (dharaonline.org) is a premier digital indexing resource providing access to international indexed papers on Ayurveda.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'In Hospital Information Management Systems (HIMS), what digital feature ensures data privacy and role-based security compliance under the Digital Personal Data Protection (DPDP) Act?',
        'question_type': 'mcq',
        'option_a': 'Role-Based Access Control (RBAC) with end-to-end encryption and audit logging of who views or edits electronic health records',
        'option_b': 'Sharing master passwords on sticky notes',
        'option_c': 'Making all patient case sheets publicly searchable without login',
        'option_d': 'Disabling all password authentication completely',
        'correct_answer': 'A',
        'explanation': 'RBAC and encryption ensure that only authorized clinicians can access sensitive patient medical data, maintaining compliance and confidentiality.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'Which digital pulse diagnostic instrument uses piezoelectric sensors and machine learning algorithms to capture radial pulse waveform data and map it to Vata, Pitta, and Kapha curves?',
        'question_type': 'mcq',
        'option_a': 'Nadi Tarangini / Computerized Nadi Pariksha systems',
        'option_b': 'Standard mercury barometer',
        'option_c': 'Analog wall clock',
        'option_d': 'Tuning fork',
        'correct_answer': 'A',
        'explanation': 'Nadi Tarangini captures arterial pressure waveforms from the radial artery using tactile pressure transducers, offering digital pulse waveform analysis.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'In biomedical statistical data analysis of a clinical trial dataset, which software tool is commonly utilized for conducting parametric (t-tests, ANOVA) and non-parametric tests?',
        'question_type': 'mcq',
        'option_a': 'SPSS / R / Python (SciPy & Statsmodels)',
        'option_b': 'Basic text editor without formula support',
        'option_c': 'Video editing software',
        'option_d': 'Graphic paint tool',
        'correct_answer': 'A',
        'explanation': 'SPSS, R, and Python provide robust statistical computing libraries for medical research hypotheses testing and data analytics.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'When writing and managing citations for an academic research paper in Ayurveda, which digital reference management tool automates bibliography generation in APA, Vancouver, or Harvard styles?',
        'question_type': 'mcq',
        'option_a': 'Zotero / Mendeley / EndNote',
        'option_b': 'Calculator application',
        'option_c': 'System sound mixer',
        'option_d': 'Webcam utility',
        'correct_answer': 'A',
        'explanation': 'Zotero, Mendeley, and EndNote enable researchers to organize papers, insert in-text citations, and generate formatted bibliographies automatically.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'What is the Ayush Grid initiative launched by the Ministry of AYUSH?',
        'question_type': 'mcq',
        'option_a': 'An overarching digital transformation project creating a unified IT backbone for AYUSH healthcare delivery, telemedicine, education, research, and drug regulatory governance across India',
        'option_b': 'An electricity power transmission grid',
        'option_c': 'A railway reservation network',
        'option_d': 'A highway toll monitoring program',
        'correct_answer': 'A',
        'explanation': 'Ayush Grid is the comprehensive digital initiative integrating electronic health records, telemedicine, hospital information systems, and research portals nationwide.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Digital Skills',
        'question_text': 'Under the Ayushman Bharat Digital Mission (ABDM), what digital health identifier is assigned to citizens to link their health records seamlessly across AYUSH and modern hospitals?',
        'question_type': 'mcq',
        'option_a': 'ABHA (Ayushman Bharat Health Account) Number',
        'option_b': 'Driving License Number',
        'option_c': 'Vehicle Registration plate',
        'option_d': 'PAN card number exclusively',
        'correct_answer': 'A',
        'explanation': 'ABHA is a 14-digit unique health ID that allows patients to share and access their digital health records across participating healthcare providers.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },

    # =========================================================================
    # 10. SHALYA TANTRA (10 Questions)
    # =========================================================================
    {
        'skill': 'Shalya Tantra',
        'question_text': 'What are the three canonical medicinal substances sequentially layered onto the surgical linen thread during the classical preparation of Apamarga Ksharasutra?',
        'question_type': 'mcq',
        'option_a': 'Ghee, Honey, and Triphala powder',
        'option_b': 'Snuhi Ksheera (Euphorbia nerifolia latex), Apamarga Kshara (Achyranthes aspera alkali), and Haridra Churna (Curcuma longa powder)',
        'option_c': 'Castor oil, Neem juice, and Sandalwood paste',
        'option_d': 'Kajjali, Guggulu, and Tulsi extract',
        'correct_answer': 'B',
        'explanation': 'Classical Ksharasutra utilizes 11 coatings of Snuhi Ksheera, 7 coatings of Snuhi Ksheera + Apamarga Kshara, and 3 coatings of Snuhi Ksheera + Haridra Churna (21 total coatings).',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'In the classical management of Bhagandara (Fistula-in-ano), why is Ksharasutra therapy globally recognized as superior to standard fistulectomy excision?',
        'question_type': 'mcq',
        'option_a': 'It requires prolonged general anesthesia and complete hospital confinement',
        'option_b': 'It achieves simultaneous mechanical cutting (Chhedana) and chemical healing (Ropana) without damaging the anal sphincter, yielding near-zero fecal incontinence and low recurrence',
        'option_c': 'It completely avoids any local examination',
        'option_d': 'It requires no dressing or follow-up rethreading',
        'correct_answer': 'B',
        'explanation': 'Ksharasutra simultaneously cuts and promotes healthy granulation tissue from the base outward, preserving sphincter muscle integrity and preventing recurrence.',
        'difficulty': 'Medium',
        'marks': 2.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'Which classical decoction is indicated for therapeutic wound cleaning (Vrana Prakshalana) to eliminate slough, bacteria, and discharge in an infected chronic wound (Dushta Vrana)?',
        'question_type': 'mcq',
        'option_a': 'Drakshasava',
        'option_b': 'Triphala Kwatha / Panchavalkala Kwatha',
        'option_c': 'Brahmi Ghrita',
        'option_d': 'Chandanasava',
        'correct_answer': 'B',
        'explanation': 'Triphala Kwatha and Panchavalkala Kwatha possess potent Kashaya Rasa, Shodhana (cleansing), and Ropana (healing) actions, making them the gold standard for Vrana Prakshalana.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'What is the prime clinical indication for applying Agnikarma (Thermal micro-cauterization) with Shalaka in classical Ayurvedic surgery?',
        'question_type': 'mcq',
        'option_a': 'Severe acute Pitta-Rakta inflammation and burns',
        'option_b': 'Intractable Vata-Kaphaja pain, heel spur (Vatakantaka), chronic tendonitis (Snayugata Vata), and joint stiffness refractory to medications',
        'option_c': 'Open weeping eczema lesions exclusively',
        'option_d': 'Severe internal bleeding disorders',
        'correct_answer': 'B',
        'explanation': 'Agnikarma utilizes heat to instantly relieve severe deep-seated Vata-Kapha pain in ligaments, joints, and tendons ("Agnina Dahati Na Punarbhavati").',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'Which modality of Raktamokshana (Bloodletting) is uniquely indicated for delicate patients, women, children, and localized Pitta-Rakta vitiated ulcers (Dushta Vrana)?',
        'question_type': 'mcq',
        'option_a': 'Jalaukavacharana (Medicinal Leech therapy)',
        'option_b': 'Siravyadha (Major venous puncture with large trocars)',
        'option_c': 'Alabu (Gourd suction) for dry Kapha disorders',
        'option_d': 'Pracchana (Multiple scalpel scarifications)',
        'correct_answer': 'A',
        'explanation': 'Jalauka (Hirudo medicinalis / medicinal leeches) are Sheeta and Jala-ja in origin, making them the gentlest modality for localized Pitta-Rakta disorders.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'According to Sushruta Samhita, what are the Ashtavidha Shastra Karma (eight classical surgical procedures)?',
        'question_type': 'mcq',
        'option_a': 'Chedana (Excision), Bhedana (Incision), Lekhana (Scraping), Vyadhana (Puncturing), Eshana (Probing), Aharana (Extraction), Visravana (Draining), and Seevana (Suturing)',
        'option_b': 'Snehana, Swedana, Vamana, Virechana, Basti, Nasya, Raktamokshana, Shirodhara',
        'option_c': 'Deepana, Pachana, Kshuda, Trishna, Vyayama, Atapa, Maruta',
        'option_d': 'Darshana, Sparshana, Prashna, Nadi, Mutra, Mala, Jihva, Shabda',
        'correct_answer': 'A',
        'explanation': 'Sushruta canonically defines the eight fundamental surgical operations: Chedana, Bhedana, Lekhana, Vyadhana, Eshana, Aharana, Visravana, and Seevana.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'Which classical instrument is utilized in Sushruta surgery for exploring the direction and depth of a sinus or fistulous tract (Bhagandara / Nadi Vrana)?',
        'question_type': 'mcq',
        'option_a': 'Eshani (Surgical Probe / Director)',
        'option_b': 'Vranadhupana apparatus',
        'option_c': 'Sandamsha Yantra (Forceps)',
        'option_d': 'Tala Yantra',
        'correct_answer': 'A',
        'explanation': 'Eshani is a probe used to explore tracts, channels, and foreign bodies (Eshana Karma).',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'What is the classical formulation applied for promoting rapid granulation tissue formation and wound healing (Vrana Ropana) in a cleansed ulcer?',
        'question_type': 'mcq',
        'option_a': 'Jatyadi Taila / Jatyadi Ghrita',
        'option_b': 'Chitrakadi Vati',
        'option_c': 'Lavangadi Vati',
        'option_d': 'Laxmi Vilas Rasa',
        'correct_answer': 'A',
        'explanation': 'Jatyadi Taila containing Jati, Nimba, Patola, Katuki, and Haridra is the premier classical Ropana medicated oil for wound healing.',
        'difficulty': 'Easy',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'In the management of 2nd and 3rd-degree internal hemorrhoids (Arsha), which para-surgical procedure is indicated for achieving chemical necrosis and sloughing without open cutting?',
        'question_type': 'mcq',
        'option_a': 'Pratisaraneeya Kshara application',
        'option_b': 'Cryotherapy with dry ice',
        'option_c': 'Heavy Snehana massage',
        'option_d': 'Intramuscular antibiotics injection',
        'correct_answer': 'A',
        'explanation': 'Pratisaraneeya Kshara (caustic alkaline paste) causes chemical coagulation necrosis of hemorrhoidal tissue, leading to safe sloughing and fibrosis.',
        'difficulty': 'Medium',
        'marks': 1.0,
    },
    {
        'skill': 'Shalya Tantra',
        'question_text': 'According to Sushruta, what are the four cardinal classical signs indicating that a wound has achieved full healthy healing (Samyak Roodha Vrana)?',
        'question_type': 'mcq',
        'option_a': 'Asamutsanna (Flush with surrounding skin), Avedana (Painless), Asrava (Discharge-free), and Sthira (Stable supple scar tissue matching normal skin color)',
        'option_b': 'Severe purulent discharge and bleeding',
        'option_c': 'Elevated hyperkeratotic keloid formation',
        'option_d': 'Persistent fiery burning sensation and ulceration',
        'correct_answer': 'A',
        'explanation': 'Sushruta defines a healed wound (Roodha Vrana) as level with the skin surface, completely pain-free, non-discharging, and restored to tissue integrity.',
        'difficulty': 'Hard',
        'marks': 1.0,
    },
]


class Command(BaseCommand):
    help = 'Seed database with sample skills, assessments, courses, career paths, regional opportunities, validation questions, and demo users'

    def handle(self, *args, **options):
        self.stdout.write('Seeding database...')

        # Create skills
        skills = {}
        for name, category in SKILLS_DATA:
            skill, _ = Skill.objects.get_or_create(
                skill_name=name,
                defaults={'category': category, 'description': f'{name} competency skill'},
            )
            skills[name] = skill
        self.stdout.write(f'  Created {len(skills)} skills')

        # Create Career Paths and Skill Requirements
        career_paths_created = 0
        career_path_map = {}
        for cp_data in CAREER_PATHS_DATA:
            cp, _ = CareerPath.objects.get_or_create(
                name=cp_data['name'],
                defaults={
                    'career_category': cp_data['category'],
                    'description': cp_data['description'],
                    'is_active': True,
                },
            )
            career_path_map[cp_data['name']] = cp
            career_paths_created += 1

            for s_name, req_score, weight, priority in cp_data['skills']:
                skill = skills.get(s_name)
                if skill:
                    CareerPathSkillRequirement.objects.update_or_create(
                        career_path=cp,
                        skill=skill,
                        defaults={
                            'required_score': req_score,
                            'importance_weight': weight,
                            'priority_level': priority,
                        },
                    )

        self.stdout.write(f'  Created {career_paths_created} Career Paths with competency requirements')

        # Create assessment questions
        count = 0
        for category, questions in ASSESSMENT_DATA.items():
            skill = skills.get(category, list(skills.values())[0])
            for q_text in questions:
                Assessment.objects.get_or_create(
                    question_text=q_text,
                    defaults={
                        'skill': skill,
                        'question_type': 'scale',
                        'max_score': 5,
                        'category': category,
                    },
                )
                count += 1
        self.stdout.write(f'  Created {count} assessment questions')

        # Create courses
        for name, skill_name, level, provider, is_free in COURSES_DATA:
            skill = skills.get(skill_name)
            if skill:
                Course.objects.get_or_create(
                    course_name=name,
                    defaults={
                        'skill': skill,
                        'level': level,
                        'provider': provider,
                        'link': f'https://example.com/courses/{name.lower().replace(" ", "-")}',
                        'duration': '4 weeks',
                        'is_free': is_free,
                    },
                )
        self.stdout.write(f'  Created {len(COURSES_DATA)} courses')

        # Seed Concept Validation Questions (Layer 2)
        from skills.models import ValidationQuestion
        val_q_count = 0
        for vq in VALIDATION_QUESTIONS_DATA:
            skill_obj = skills.get(vq['skill'])
            if skill_obj:
                ValidationQuestion.objects.update_or_create(
                    skill=skill_obj,
                    question_text=vq['question_text'],
                    defaults={
                        'question_type': vq.get('question_type', 'mcq'),
                        'case_context': vq.get('case_context', ''),
                        'option_a': vq['option_a'],
                        'option_b': vq['option_b'],
                        'option_c': vq['option_c'],
                        'option_d': vq['option_d'],
                        'correct_answer': vq['correct_answer'],
                        'explanation': vq.get('explanation', ''),
                        'difficulty': vq.get('difficulty', 'Medium'),
                        'marks': vq.get('marks', 1.0),
                        'is_active': True,
                    }
                )
                val_q_count += 1
        self.stdout.write(f'  Seeded {val_q_count} Concept Validation Questions across Ayurvedic domains')

        # Create admin user
        if not User.objects.filter(username='admin').exists():
            admin_user = User.objects.create_superuser('admin', 'admin@ayurvedaportal.com', 'admin123')
            admin_user.profile.role = 'ADMIN'
            admin_user.profile.email_verified = True
            admin_user.profile.save()
            self.stdout.write('  Created admin user (admin/admin123)')

        # Seed South Indian & national opportunities idempotently with dedicated user accounts
        opps_seeded = 0
        for idx, item in enumerate(OPPORTUNITIES_DATA):
            company_name = item['company']
            company_type = item.get('company_type', 'Hospital')
            loc = item['location']
            st = item.get('state', '')

            # Create or get distinct user for each industry entity
            cleaned_slug = re.sub(r'[^a-zA-Z0-9_]', '_', company_name.lower())[:20]
            ind_username = f"ind_{cleaned_slug}_{idx}"
            ind_user, _ = User.objects.get_or_create(
                username=ind_username,
                defaults={'email': f'{ind_username}@demo.com'}
            )
            if not ind_user.has_usable_password():
                ind_user.set_password('demo123')
                ind_user.save()
            if hasattr(ind_user, 'profile'):
                ind_user.profile.role = 'INDUSTRY'
                ind_user.profile.email_verified = True
                ind_user.profile.save()

            # Create or get industry record
            ind_obj = Industry.objects.filter(company_name=company_name).first()
            if not ind_obj:
                ind_obj = Industry.objects.create(
                    user=ind_user,
                    company_name=company_name,
                    type=company_type,
                    location=loc,
                    website='https://example.com',
                    verified_status=item.get('data_status') == 'VERIFIED',
                )

            # Idempotently update_or_create opportunity
            opp, _ = Opportunity.objects.update_or_create(
                title=item['title'],
                location=loc,
                defaults={
                    'industry': ind_obj,
                    'type': item['type'],
                    'state': st,
                    'data_status': item.get('data_status', 'NEEDS_VERIFICATION'),
                    'description': item['description'],
                    'duration': item.get('duration', '3 months'),
                    'stipend_salary': item.get('stipend', ''),
                    'eligibility': item.get('eligibility', 'BAMS students / graduates'),
                    'is_active': True,
                },
            )

            # Seed specific skill requirements
            for s_name, req_score, s_weight in item.get('skills', []):
                skill_obj = skills.get(s_name)
                if skill_obj:
                    OpportunitySkill.objects.update_or_create(
                        opportunity=opp,
                        skill=skill_obj,
                        defaults={
                            'required_score': req_score,
                            'weight': s_weight,
                        },
                    )
            opps_seeded += 1

        self.stdout.write(f'  Seeded {opps_seeded} Ayurvedic opportunities across all regions of India')

        # Create demo student
        if not User.objects.filter(username='demo_student').exists():
            stu_user = User.objects.create_user('demo_student', 'student@demo.com', 'demo123')
            stu_user.profile.role = 'STUDENT'
            stu_user.profile.email_verified = True
            stu_user.profile.save()
            demo_cp = career_path_map.get('Ayurvedic Clinical Practitioner')
            student = Student.objects.create(
                user=stu_user,
                name='Demo Student',
                email='student@demo.com',
                college='National Institute of Ayurveda',
                course='BAMS',
                year=3,
                specialization='Kayachikitsa',
                career_path=demo_cp,
                career_goal='Ayurvedic Clinical Practitioner',
            )
            # Add sample skill scores
            for skill_name, skill in skills.items():
                StudentSkill.objects.create(
                    student=student,
                    skill=skill,
                    score=random.randint(30, 90),
                )
            self.stdout.write('  Created demo student (demo_student/demo123)')
        else:
            # Update demo student career path if missing
            student = Student.objects.filter(user__username='demo_student').first()
            if student and not student.career_path:
                demo_cp = career_path_map.get('Ayurvedic Clinical Practitioner')
                student.career_path = demo_cp
                student.career_goal = demo_cp.name if demo_cp else 'Ayurvedic Clinical Practitioner'
                student.save()

        self.stdout.write(self.style.SUCCESS('Database seeded successfully!'))
'''

final_content = header + new_validation_data_and_command

with open(seed_path, 'w', encoding='utf-8') as f:
    f.write(final_content)

print("Updated seed_data.py successfully!")
