# Generated by Django 4.2.30 on 2026-08-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Clinical', 'Clinical'), ('Research', 'Research'), ('Soft Skill', 'Soft Skill'), ('Professional', 'Professional'), ('Digital', 'Digital'), ('Ayurveda Knowledge', 'Ayurveda Knowledge'), ('Communication', 'Communication'), ('Documentation', 'Documentation')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('scale', 'Scale (1-5)'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No')], default='scale', max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=5)),
                ('category', models.CharField(max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='skills.skill')),
            ],
            options={
                'ordering': ['category', 'assessment_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('assessment_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='skills.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
