# Generated by Django 4.2.30 on 2026-08-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('career_category', models.CharField(choices=[('Clinical Practice', 'Clinical Practice'), ('Clinical Specialization', 'Clinical Specialization'), ('Research & Development', 'Research & Development'), ('Pharmaceutical & Dravyaguna', 'Pharmaceutical & Dravyaguna'), ('Healthcare Management', 'Healthcare Management'), ('Public Health', 'Public Health'), ('Medical Communications', 'Medical Communications'), ('Wellness & Entrepreneurship', 'Wellness & Entrepreneurship')], default='Clinical Practice', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'ordering': ['career_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPathSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_score', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('importance_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=20)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='skills.careerpath')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_path_requirements', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Career Path Skill Requirement',
                'verbose_name_plural': 'Career Path Skill Requirements',
                'ordering': ['-importance_weight', '-required_score'],
                'unique_together': {('career_path', 'skill')},
            },
        ),
    ]
