# Generated by Django 4.2.30 on 2026-08-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_careerpath_careerpathskillrequirement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='careerpathskillrequirement',
            constraint=models.UniqueConstraint(fields=('career_path', 'skill'), name='unique_career_path_skill_req'),
        ),
    ]
