# Generated by Django on 2026-08-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('skills', '0003_careerpathskillrequirement_unique_career_path_skill_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskill',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Whether validated through concept test'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='self_assessment_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Raw Self-Assessment Score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='validated_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Validated Concept Test Score (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentskill',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Active/Verified Skill Score', max_digits=5),
        ),
        migrations.CreateModel(
            name='ValidationQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('case_study', 'Case-Based Clinical Scenario')], default='mcq', max_length=20)),
                ('case_context', models.TextField(blank=True, default='', help_text='Optional clinical case scenario or background')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, default='', help_text='Classical Ayurvedic or clinical explanation')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_questions', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Validation Question',
                'verbose_name_plural': 'Validation Questions',
                'ordering': ['skill', 'difficulty', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptValidationAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('skill_scores', models.JSONField(blank=True, default=dict, help_text='Skill-wise score breakdown')),
                ('is_latest', models.BooleanField(default=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_attempts', to='skills.careerpath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_attempts', to='students.student')),
            ],
            options={
                'verbose_name': 'Concept Validation Attempt',
                'verbose_name_plural': 'Concept Validation Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptValidationAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skills.conceptvalidationattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='skills.validationquestion')),
            ],
            options={
                'verbose_name': 'Validation Answer',
                'verbose_name_plural': 'Validation Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
